### ISSUE TITLE
Player UI not updating when playing next track from itemlist

### ISSUE THREAD

**Issue by stigi** [nexxtv/nexxPLAY-android#3]
Hi there,

I work with @AndreaLoden and want to follow up on #1 on his behalf.

We added `itemlist` successfully, but the player UI does not update when the next track in a playlist is played. I.e. the behavior is as such:

- The video duration is updated & the play progress moves along
- The title and subtitle of the video stay the same as from the previous item

I didn't dig deep into the issue yet, but let me know if you need further details to debug the issue.

Thanks

**Comment by mfentross** [comment]
Hi @stigi ,

thank you for reporting this issue. Could you please provide me with the parameter string (or an example of it) you use in startPlay()?

Thanks in advance!

**Comment by stigi** [comment]
@mfentross I believe we just use a comma separated list of IDs like `1544504,1544291,1536877`

The code looks something like this

```kotlin
interface NexxPlayerAPI : NexxPlayer, NexxPlayerAndroid, NexxPlayerNotification {}
//...
val nexxPlayer: NexxPlayerAPI by lazy { NexxFactory.createNexxPlayer(this) as NexxPlayerAPI }
//...
val mediaId = "1544504,1544291,1536877"
nexxPlayer.startPlay(
                null,
                CUSTOMER_ID,
                PlayMode.itemlist,
                mediaId,
                0,
                0)
```

BTW: is there a reason why `NexxFactory.createNexxPlayer` returns only `NexxPlayerAndroid` and we have to typecast to do simple things like `startPlay`?

**Comment by stigi** [comment]
@mfentross This issue is still unresolved as of Nexx player version 3.2.2.

Any updates?

**Comment by mfentross** [comment]
Hi @stigi , sorry for the delay. This issue has been fixed in 3.2.18

> BTW: is there a reason why NexxFactory.createNexxPlayer returns only NexxPlayerAndroid and we have to typecast to do simple things like startPlay?

Yes, we need to keep the lifecycle methods apart from the player methods.

**Comment by stigi** [comment]
Hi @mfentross,

I just updated to 3.2.18 and the issue still seems to be present.

**Comment by mfentross** [comment]
Hi @stigi ,

sorry for the late reply; I have been sick for a while now.

Could you please give me some more information about your environment (e.g. CUSTOMER_ID when the problem occurs)? Tested with 741 the problem does not appear anymore, so I assume there are some domain specific settings that are conflicting.

Thank you!

**Comment by toto** [comment]
@mfentross can you email me (email is on my GH user page) so we can discuss the issues non-public if they are site related.

**Comment by stigi** [comment]
This has been fixed for a while now. Closing.
